name: pr-build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["main"]

jobs:
  pr-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package